---
- name: Mysql | Set password selection
  sudo: yes
  raw: debconf-set-selections <<< 'mysql-server mysql-server/root_password password {{mysql_password}}'
  args:
    executable: /bin/bash
  tags: mysql

- name: Mysql | Set password confirmation selection
  sudo: yes
  raw: debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password {{mysql_password}}'
  args:
    executable: /bin/bash
  tags: mysql

- name: Mysql | Install mysql and related components
  sudo: yes
  apt: pkg=mysql-server
  tags: mysql

- name: Mysql | Install php mysql module
  sudo: yes
  apt: pkg=php-mysql
  tags: mysql

- name: Mysql | Install python mysql module
  sudo: yes
  apt: pkg=python-mysqldb
  tags: mysql
