---
- name: CiviCRM | Install CiviCRM Runtime Dependencies
  sudo: yes
  apt:
    pkg: "{{item}}"
  with_items: 
  - unzip
  - curl
  tags: civi

- name: CiviCRM | Download and Extract plugin
  sudo: yes
  unarchive: 
    src: "http://downloads.sourceforge.net/project/civicrm/civicrm-stable/{{ civicrm_version }}/civicrm-{{ civicrm_version }}-wordpress.zip"
    remote_src: yes
    dest: /var/www/html/wp-content/plugins 
    owner: www-data
    group: www-data
  tags: civi

- name: CiviCRM | Create the civicrm database
  sudo: yes
  mysql_db: 
    login_user: "{{mysql_user}}"
    login_password: "{{mysql_password}}"
    name: "{{civicrm_database}}"
    state: present
  tags: civi

- name: CiviCRM | Create civicrm database user
  sudo: yes
  mysql_user: login_user={{mysql_user}} login_password={{mysql_password}} name={{ civicrm_database_user }} password={{ civicrm_database_password }} priv={{ civicrm_database }}.*:ALL host='localhost' state=present
  tags: civi

- name: CiviCRM | Create files directory
  sudo: yes
  file:
    path: /var/www/html/wp-content/plugins/files
    state: directory
    owner: www-data
    group: www-data
    mode: u+rwx,go-rwx
  tags: civi

- name: CiviCRM | Make PHP Files Executable
  command: find /var/www/html/wp-content/plugins/civicrm -name *.php -exec chmod -c 0700 {} \;
  register: chmod_result
  changed_when: "chmod_result.stdout != \"\""
  tags: civi

