---
- name: PHP | Install PHP and dependencies
  sudo: yes
  apt: 
    pkg: "{{ item }}"
  with_items:
  - php
  - libapache2-mod-php
  - php-mcrypt
  - php-gd
  - php-xml
  - php-curl
  tags: php

- name: PHP | Restart server after PHP config
  sudo: yes
  service: name=apache2 state=restarted
  tags: php
